spring:
  application:
    name: hometask
  datasource:
    url: jdbc:h2:mem:hometask;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  main:
    web-application-type: none

hometask:
  input-path: classpath:input.txt
  output-path: output.txt

velocity:
  limits:
    max-daily-load-amount: 5000.00
    max-weekly-load-amount: 20000.00
    max-daily-load-count: 3
